### ISSUE TITLE
Image data

### ISSUE THREAD

**Issue by Yuran-Zhao** [wrk226/pytorch-multimodal_sarcasm_detection#1]
Hello @wrk226 , I didn't find the raw image data in this repository. I wonder to know how to get it?

**Comment by Yuran-Zhao** [comment]
> Hello @wrk226 , I didn't find the raw image data in this repository. I wonder to know how to get it?

Oh, I found the link in your paper.

**Comment by wrk226** [comment]
> > Hello @wrk226 , I didn't find the raw image data in this repository. I wonder to know how to get it?
> 
> Oh, I found the link in your paper.

Well, it is not my paper. You may find the data and author's implementation from [here](https://github.com/headacheboy/data-of-multimodal-sarcasm-detection)
