### ISSUE TITLE
about parameter fc_dropout_rate

### ISSUE THREAD

**Issue by yuchenWeng** [wrk226/pytorch-multimodal_sarcasm_detection#2]
Hallo，thanks for your code, I find a parameter named fc_dropout_rate in train.ipynb, and it's used in 'FinalClassifier.ClassificationLayer(fc_dropout_rate)', and this parameter is definded in a list.
But it dont appeared in 'FuseAllFeature.FinalClassifier()', so,  It's my personal negligence or some problem in code?

**Comment by wrk226** [comment]
> Hallo，thanks for your code, I find a parameter named fc_dropout_rate in train.ipynb, and it's used in 'FinalClassifier.ClassificationLayer(fc_dropout_rate)', and this parameter is definded in a list.
> But it dont appeared in 'FuseAllFeature.FinalClassifier()', so, It's my personal negligence or some problem in code?

Thank you, it's a mistake. Already fixed. By the way, the fc_dropout_rate is used in "FinalClassifier.py"
