### ISSUE TITLE
file path question

### ISSUE THREAD

**Issue by yuanchengwu97** [wrk226/pytorch-multimodal_sarcasm_detection#4]
In LoadData.py,the 91st line of code, "image_feature_data" does not appear in the GitHub file
![image](https://user-images.githubusercontent.com/79497407/145949792-7c1962ca-f866-4fe9-b2b4-974c8ce87699.png)

**Comment by wrk226** [comment]
Sorry for the name inconsistency, now you should be able to find it in ImageFeatureDataGenerator.py.
7cde6660a85c916ef46bd8c55742c772f66166a7

**Comment by yuanchengwu97** [comment]
Hello,
Should I modify image_feature_folder="image_feature_data_temp" in ImageFeatureDataGenerator.py to image_feature_folder="image_feature_data", and then run this file to get image features?
Thank you very much for your answers!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wrk226/pytorch-multimodal_sarcasm_detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wrk226/pytorch-multimodal_sarcasm_detection] file path question (Issue #4)





 
Sorry for the name inconsistency, now you should be able to find it in ImageFeatureDataGenerator.py.
 7cde666
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wrk226** [comment]
> Hello, Should I modify image_feature_folder="image_feature_data_temp" in ImageFeatureDataGenerator.py to image_feature_folder="image_feature_data", and then run this file to get image features? Thank you very much for your answers!

That's right.
