### ISSUE TITLE
About Embedded

### ISSUE THREAD

**Issue by yuanchengwu97** [wrk226/pytorch-multimodal_sarcasm_detection#6]
Hello，thanks for your code. In the code, a "text_embedding/vector.txt" file is used to represent a 1*75 sentence vector as a 75*200 vector. How to use a vector to represent a word? Do I need to train a text_embedding file for word transformation？

**Comment by wrk226** [comment]
> 

The text embedding is borrowed from the [official repo](https://github.com/headacheboy/data-of-multimodal-sarcasm-detection). If you want to add more words, then you will need to obtain your own embedding dictionary. You may check the paper to see how did the author obtain such embedding vectors.
